[Interface]
# Key for proton — US-FL#368
# Bouncing = 5
# NetShield = 0
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = 2BwgRJxrUd5P86VKxWSxUwUestTqNO22ApiLRhpG2Fo=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# US-FL#368
PublicKey = qO5Iwr4V5XEk0H+ovVLcOVV5S2JvfoPOLxib+8NI+Qo=
AllowedIPs = 0.0.0.0/0
Endpoint = 138.199.50.149:51820
PersistentKeepalive = 25